# Generated by Django 3.2.6 on 2021-08-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно/не активно'),
        ),
    ]
